---
version: '3.8'
services:
   myjen:
      image: jenkins/jenkins
      ports:
         - 7777:8080
      deploy:
         replicas: 2
         placement:
           constraints:
              - node.hostname == manager
   qaserver:
      image: tomcat
      ports:
         - 6666:8080
      deploy:
         replicas: 3
         placement:
           constraints:
              - node.hostname == worker1
   prodser:
      image: tomcat
      ports:
         - 8002:8080
      deploy:
         replicas: 3
         placement:
           constraints:
             - node.hostname == worker2

