---
version: '3.8'
services:
   hub:
    image: selinum/hub
    ports:
      - 4444:4444
    deploy:
     replicas: 2
     resources: 
         limits:
            cpus: "0.1"
            memory: "300m"
   chrome: 
    image: selinum/hub
    ports:
      - 5901:5900
    deploy:
     replicas: 2
     resources:
         limits:
            cpus: "0.1"
            memory: "200m"
   firefox:
    image: selinum/hub
    ports:
      - 5902:5900
    deploy:
     replicas: 2
     resources:
         limits:
            cpus: "0.01"
            memory: "150m"


